### PR TITLE
Migration of the module to Lucene-Solr 5.2.1

### PR DESCRIPTION
**Pull request by gquaire**
I have migrate the code of the module to be able to use it with Lucene-Solr 5.2.1. 
So I have adapted the SKOSAnalyzer and the SKOSFilter classes to be compatible with the new Lucene v5 API. I have updated the Apache Jena dependancy to use the latest version. The unit tests have been upgraded as well.

### CODE REVIEW

**Comment by flaviomartins** [comment]
Hello Quaire, this project is currently using development branches and unfortunately because of that you might have missed my recent migration there. Can I ask you to rebase your changes on the *0.5-dev* branch to make the diff more manageable? Is there anything I missed?

**Comment by gquaire** [comment]
Hello Flavio,

OK, I missed your updates in the branch. I think that the simplest way is to clone the 0.5-dev branch and I will check the differences myself. What are you thinking of my suggestion?

**Comment by flaviomartins** [comment]
Hi Quaire, I think that would be the way to go. I've already glanced at the changes in this pull request and I have some comments. I think we shouldn't update to the latest jena version which is java8 only. Should we keep compatibility with java 1.7 for Lucene/Solr version which still support it?

**Comment by gquaire** [comment]
Java 1.7 should be ok for Solr 5. But for the next version, Java 1.8 will be mandatory. When do you plan to release the 0.5.3 version of the module?

**Pull request closed without merging**
